version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend/backend
    container_name: crm_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crm_db
      SPRING_DATASOURCE_USERNAME: crm_user
      SPRING_DATASOURCE_PASSWORD: crm_password

  frontend:
    build: ./frontend/frontend
    container_name: crm_frontend
    ports:
      - "4200:80"
