using Backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CRM.API.Migrations
{
    /// <summary>
    /// Module analyse d'appels IA porté depuis khaled-dev-v3 : appels analysés, RDV détectés,
    /// RDV CRM, relances, messagerie interne, données sauvegardées agent, logs, leads.
    /// Idempotent (IF NOT EXISTS) comme les autres migrations manuelles des modules Khaled.
    /// Script SQL équivalent : scripts/sql/add_call_analysis_module.sql
    /// </summary>
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929120000_AddCallAnalysisModule")]
    public partial class AddCallAnalysisModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS calls (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""AgentId"" character varying(50) NOT NULL,
    ""AgentName"" character varying(150) NOT NULL,
    ""AgentPoliteness"" integer NOT NULL,
    ""AgentSeconds"" real NOT NULL,
    ""AgentTalkRatio"" real NOT NULL,
    ""AgentText"" text,
    ""AppointmentConfidence"" integer NOT NULL,
    ""AppointmentDate"" character varying(100),
    ""AudioFile"" character varying(500),
    ""CallDate"" timestamp with time zone,
    ""CallDuration"" integer,
    ""CallType"" character varying(50),
    ""ClientSeconds"" real NOT NULL,
    ""ClientTalkRatio"" real NOT NULL,
    ""ClientText"" text,
    ""CoherenceScore"" real,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""CustomerIntent"" character varying(100),
    ""DiarizationMethod"" character varying(20) NOT NULL,
    ""InactivityDetected"" boolean NOT NULL,
    ""InactivityDuration"" real NOT NULL,
    ""Keywords"" text,
    ""LabeledTranscript"" text,
    ""LeadId"" integer,
    ""NextSteps"" text,
    ""ObjectionsHandled"" boolean NOT NULL,
    ""Performance"" character varying(50),
    ""PostalCode"" character varying(10),
    ""Problem"" character varying(200),
    ""Qualification"" character varying(100),
    ""QualificationCoherence"" boolean,
    ""QualificationMatch"" boolean,
    ""RefusalReason"" character varying(200),
    ""ScoreAccueil"" integer NOT NULL,
    ""ScoreArgumentation"" integer NOT NULL,
    ""ScoreClient"" integer NOT NULL,
    ""ScoreConclusion"" integer NOT NULL,
    ""ScoreEcoute"" integer NOT NULL,
    ""ScoreEfficacite"" integer NOT NULL,
    ""ScoreEmpathie"" integer NOT NULL,
    ""ScoreEnergie"" integer NOT NULL,
    ""ScoreOperateur"" integer NOT NULL,
    ""ScorePercentage"" real NOT NULL,
    ""ScorePersuasion"" integer NOT NULL,
    ""ScoreRefus"" integer NOT NULL,
    ""ScoreVente"" integer NOT NULL,
    ""ScoreVoix"" integer NOT NULL,
    ""ScriptRespected"" boolean NOT NULL,
    ""Sentiment"" character varying(20),
    ""SentimentScore"" real NOT NULL,
    ""Status"" text,
    ""Summary"" text,
    ""Transcription"" text,
    ""TranscriptionStatus"" character varying(20),
    CONSTRAINT ""PK_calls"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS ""LeadFolders"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Campaign"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""Name"" text NOT NULL,
    CONSTRAINT ""PK_LeadFolders"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS leads (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Address"" text,
    ""AgentId"" bigint,
    ""CampaignName"" text,
    ""CompanyName"" text,
    ""ContactName"" text,
    ""Email"" text,
    ""Phone"" text,
    ""PostalCode"" text,
    ""Status"" text,
    CONSTRAINT ""PK_leads"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS logs (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Action"" character varying(100),
    ""Details"" text,
    ""Timestamp"" timestamp with time zone NOT NULL,
    ""UserId"" character varying(50),
    CONSTRAINT ""PK_logs"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS ""Qualifications"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Code"" text NOT NULL,
    ""ExpectedKeywords"" text,
    ""Label"" text NOT NULL,
    CONSTRAINT ""PK_Qualifications"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS appointments (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""AgentIdRef"" character varying(50) NOT NULL,
    ""CallId"" integer NOT NULL,
    ""ClientName"" character varying(100),
    ""ClientPhone"" character varying(20),
    ""ConfidenceScore"" integer NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""DetectedDate"" character varying(100),
    ""FinalDate"" timestamp with time zone,
    ""Notes"" text,
    ""Status"" character varying(20) NOT NULL,
    CONSTRAINT ""PK_appointments"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_appointments_calls_CallId"" FOREIGN KEY (""CallId"") REFERENCES calls (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent_saved_data (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""AgentId"" bigint NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""DataType"" character varying(50) NOT NULL,
    ""Payload"" text,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_agent_saved_data"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_agent_saved_data_Utilisateur_AgentId"" FOREIGN KEY (""AgentId"") REFERENCES ""Utilisateur"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS crm_appointments (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""AgentId"" bigint NOT NULL,
    ""AppointmentDate"" timestamp with time zone NOT NULL,
    ""AppointmentTime"" character varying(10) NOT NULL,
    ""Chauffage"" character varying(50) NOT NULL,
    ""ClientEmail"" character varying(150),
    ""ClientName"" character varying(150) NOT NULL,
    ""ClientPhone"" character varying(30),
    ""Consommation"" real NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""CreditScore"" integer NOT NULL,
    ""FinancingStatus"" character varying(50) NOT NULL,
    ""Isolation"" character varying(50) NOT NULL,
    ""Notes"" text,
    ""ProjectType"" character varying(50) NOT NULL,
    ""QualityScore"" integer NOT NULL,
    ""Revenus"" real NOT NULL,
    ""SituationBancaire"" character varying(50) NOT NULL,
    ""Status"" character varying(30) NOT NULL,
    ""Toiture"" character varying(50) NOT NULL,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_crm_appointments"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_crm_appointments_Utilisateur_AgentId"" FOREIGN KEY (""AgentId"") REFERENCES ""Utilisateur"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""SenderId"" bigint NOT NULL,
    ""ReceiverId"" bigint NOT NULL,
    ""Content"" text NOT NULL,
    ""IsRead"" boolean NOT NULL,
    ""IsUrgent"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""ReadAt"" timestamp with time zone,
    CONSTRAINT ""PK_messages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_messages_Utilisateur_ReceiverId"" FOREIGN KEY (""ReceiverId"") REFERENCES ""Utilisateur"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_messages_Utilisateur_SenderId"" FOREIGN KEY (""SenderId"") REFERENCES ""Utilisateur"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""Followups"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""ContactId"" bigint,
    ""AgentId"" bigint,
    ""Status"" character varying(50) NOT NULL,
    ""AgentName"" text,
    ""AppointmentDate"" timestamp with time zone NOT NULL,
    ""RelanceCount"" integer NOT NULL,
    ""Notes"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Followups"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Followups_Contacts_ContactId"" FOREIGN KEY (""ContactId"") REFERENCES ""Contacts"" (""Id""),
    CONSTRAINT ""FK_Followups_Utilisateur_AgentId"" FOREIGN KEY (""AgentId"") REFERENCES ""Utilisateur"" (""Id"")
);

CREATE INDEX IF NOT EXISTS ""IX_agent_saved_data_AgentId"" ON agent_saved_data (""AgentId"");

CREATE INDEX IF NOT EXISTS ""IX_appointments_CallId"" ON appointments (""CallId"");

CREATE INDEX IF NOT EXISTS ""IX_crm_appointments_AgentId"" ON crm_appointments (""AgentId"");

CREATE INDEX IF NOT EXISTS ""IX_Followups_AgentId"" ON ""Followups"" (""AgentId"");

CREATE INDEX IF NOT EXISTS ""IX_Followups_ContactId"" ON ""Followups"" (""ContactId"");

CREATE INDEX IF NOT EXISTS ""IX_messages_ReceiverId"" ON messages (""ReceiverId"");

CREATE INDEX IF NOT EXISTS ""IX_messages_SenderId"" ON messages (""SenderId"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS agent_saved_data;
DROP TABLE IF EXISTS crm_appointments;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS ""Followups"";
DROP TABLE IF EXISTS calls;
DROP TABLE IF EXISTS leads;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS ""LeadFolders"";
DROP TABLE IF EXISTS ""Qualifications"";
");
        }
    }
}
