// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610135418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Agenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Backend.Entities.Appel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<string>("CheminEnregistrement")
                        .HasColumnType("text");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureeSecondes")
                        .HasColumnType("integer");

                    b.Property<bool>("Enregistre")
                        .HasColumnType("boolean");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ContactId");

                    b.ToTable("Appels");
                });

            modelBuilder.Entity("Backend.Entities.Conge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommercialId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommercialId");

                    b.ToTable("Conges");
                });

            modelBuilder.Entity("Backend.Entities.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateDernierAppel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateImport")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateRappelPlanifie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DureeDernierAppel")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long?>("FichierImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("QualificationDetaillee")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("FichierImportId");

                    b.HasIndex("Telephone");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Backend.Entities.FichierImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateImport")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Erreurs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Importateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombreContactsImportes")
                        .HasColumnType("integer");

                    b.Property<int>("NombreErreurs")
                        .HasColumnType("integer");

                    b.Property<int>("NombreTotalLignes")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FichiersImport");
                });

            modelBuilder.Entity("Backend.Entities.Performance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NbAppels")
                        .HasColumnType("integer");

                    b.Property<int>("NbAppelsQualifies")
                        .HasColumnType("integer");

                    b.Property<int>("NbInstallations")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousAnnules")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousBruts")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousConfirmes")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousHC")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousNonSignes")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousReportes")
                        .HasColumnType("integer");

                    b.Property<int>("NbRendezVousSignes")
                        .HasColumnType("integer");

                    b.Property<bool>("ObjectifAtteint")
                        .HasColumnType("boolean");

                    b.Property<int>("ObjectifMensuel")
                        .HasColumnType("integer");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PrimeAssiduite")
                        .HasColumnType("double precision");

                    b.Property<double>("PrimeMensuelle")
                        .HasColumnType("double precision");

                    b.Property<double>("PrimeTrimestrielle")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalPrimes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "DateDebut", "DateFin");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("Backend.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Pointage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DernierAppel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PremierAppel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalSecondesTravaillees")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Date")
                        .IsUnique();

                    b.ToTable("Pointages");
                });

            modelBuilder.Entity("Backend.Entities.RendezVous", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ARecontacter")
                        .HasColumnType("boolean");

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<string>("CommentaireBanque")
                        .HasColumnType("text");

                    b.Property<long?>("CommercialId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateRendezVous")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReport")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotifRefus")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeProjet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CommercialId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("Backend.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Utilisateur", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentifiantMachine")
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur");

                    b.HasDiscriminator<string>("Role").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.HasBaseType("Backend.Entities.Utilisateur");

                    b.Property<string>("Niveau")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ADMIN");
                });

            modelBuilder.Entity("Backend.Entities.Agent", b =>
                {
                    b.HasBaseType("Backend.Entities.Utilisateur");

                    b.Property<int>("ObjectifMensuel")
                        .HasColumnType("integer");

                    b.Property<double>("PrimeAssiduite")
                        .HasColumnType("double precision");

                    b.Property<double>("SalaireBase")
                        .HasColumnType("double precision");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("AGENT");
                });

            modelBuilder.Entity("Backend.Entities.Commercial", b =>
                {
                    b.HasBaseType("Backend.Entities.Utilisateur");

                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.Property<double>("TauxCommission")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("COMMERCIAL");
                });

            modelBuilder.Entity("Backend.Entities.Confirmatrice", b =>
                {
                    b.HasBaseType("Backend.Entities.Utilisateur");

                    b.Property<string>("AgendasAccess")
                        .HasColumnType("text");

                    b.Property<string>("Specialite")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CONFIRMATRICE");
                });

            modelBuilder.Entity("Backend.Entities.Agenda", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithOne("Agenda")
                        .HasForeignKey("Backend.Entities.Agenda", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Backend.Entities.Appel", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithMany("Appels")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Contact", "Contact")
                        .WithMany("HistoriqueAppels")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Backend.Entities.Conge", b =>
                {
                    b.HasOne("Backend.Entities.Commercial", "Commercial")
                        .WithMany("Conges")
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("Backend.Entities.Contact", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithMany("Contacts")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.FichierImport", "FichierSource")
                        .WithMany("Contacts")
                        .HasForeignKey("FichierImportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("FichierSource");
                });

            modelBuilder.Entity("Backend.Entities.Performance", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithMany("Performances")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Backend.Entities.Pointage", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithMany("Pointages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Backend.Entities.Pause", "Pauses", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<bool>("AlerteEnvoyee")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("Debut")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("DureeSecondes")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long>("PointageId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("PointageId");

                            b1.ToTable("Pauses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PointageId");
                        });

                    b.Navigation("Agent");

                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("Backend.Entities.RendezVous", b =>
                {
                    b.HasOne("Backend.Entities.Agent", "Agent")
                        .WithMany("RendezVous")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Commercial", "Commercial")
                        .WithMany("RendezVous")
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Entities.Contact", "Contact")
                        .WithOne("RendezVous")
                        .HasForeignKey("Backend.Entities.RendezVous", "ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Commercial");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Backend.Entities.RolePermission", b =>
                {
                    b.HasOne("Backend.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Backend.Entities.Contact", b =>
                {
                    b.Navigation("HistoriqueAppels");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Backend.Entities.FichierImport", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Backend.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backend.Entities.Agent", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Appels");

                    b.Navigation("Contacts");

                    b.Navigation("Performances");

                    b.Navigation("Pointages");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Backend.Entities.Commercial", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
