// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601092530_AddAgentProfiles")]
    partial class AddAgentProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.AgentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DerniereActivite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_activite");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<decimal>("NoteEvaluationMoyenne")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("note_evaluation_moyenne");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ObjectifMensuel")
                        .HasColumnType("integer")
                        .HasColumnName("objectif_mensuel");

                    b.Property<decimal>("PrimeAssiduite")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prime_assiduite");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salaire_base");

                    b.Property<int>("TotalPose")
                        .HasColumnType("integer")
                        .HasColumnName("total_pose");

                    b.Property<int>("TotalRdv")
                        .HasColumnType("integer")
                        .HasColumnName("total_rdv");

                    b.Property<int>("TotalRdvAnnule")
                        .HasColumnType("integer")
                        .HasColumnName("total_rdv_annule");

                    b.Property<int>("TotalRdvConfirme")
                        .HasColumnType("integer")
                        .HasColumnName("total_rdv_confirme");

                    b.Property<int>("TotalRdvSigne")
                        .HasColumnType("integer")
                        .HasColumnName("total_rdv_signe");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_contrat");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("agent_profiles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.CampaignAgents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("Quota")
                        .HasColumnType("integer")
                        .HasColumnName("quota");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("campaign_agents", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.CampaignFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<int>("ContactsCalled")
                        .HasColumnType("integer")
                        .HasColumnName("contacts_called");

                    b.Property<int>("ContactsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("contacts_remaining");

                    b.Property<int>("ContactsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("contacts_total");

                    b.Property<DateTime?>("InjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("injected_at");

                    b.Property<int?>("InjectedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("injected_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<bool>("IsInjected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_injected");

                    b.Property<bool>("IsRecycled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recycled");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduled");

                    b.Property<DateTime?>("RecycledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recycled_at");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("ScheduleStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_status");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int?>("ScheduledByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_by_user_id");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("integer")
                        .HasColumnName("source_file_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SourceFileId");

                    b.ToTable("campaign_files", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.CampaignFileContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeChaudiere")
                        .HasColumnType("integer")
                        .HasColumnName("age_chaudiere");

                    b.Property<string>("AgentComment")
                        .HasColumnType("text")
                        .HasColumnName("agent_comment");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appointment_date");

                    b.Property<string>("AppointmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("appointment_type");

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_agent_id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("CallDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("call_duration_seconds");

                    b.Property<string>("CallStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("call_status");

                    b.Property<int>("CampaignFileId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_file_id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CommercialComment")
                        .HasColumnType("text")
                        .HasColumnName("commercial_comment");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConfirmationComment")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_comment");

                    b.Property<string>("ConfirmationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("confirmation_status");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<string>("ConsommationChauffage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consommation_chauffage");

                    b.Property<bool?>("Credits")
                        .HasColumnType("boolean")
                        .HasColumnName("credits");

                    b.Property<bool?>("EquipePAC")
                        .HasColumnType("boolean")
                        .HasColumnName("equipe_pac");

                    b.Property<bool?>("EquipePV")
                        .HasColumnType("boolean")
                        .HasColumnName("equipe_pv");

                    b.Property<string>("EtatIsolation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etat_isolation");

                    b.Property<string>("EtatToiture")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etat_toiture");

                    b.Property<bool?>("Fichage")
                        .HasColumnType("boolean")
                        .HasColumnName("fichage");

                    b.Property<DateTime?>("LastCallAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_call_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("ModeChauffage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode_chauffage");

                    b.Property<int?>("NbrePersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("nbre_personnes");

                    b.Property<DateTime?>("NextCallAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_call_at");

                    b.Property<string>("ProfessionMme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profession_mme");

                    b.Property<string>("ProfessionMr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profession_mr");

                    b.Property<string>("Projet")
                        .HasColumnType("text")
                        .HasColumnName("projet");

                    b.Property<int?>("ProprietaireDepuis")
                        .HasColumnType("integer")
                        .HasColumnName("proprietaire_depuis");

                    b.Property<string>("QualificationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("qualification_status");

                    b.Property<DateTime?>("QualifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qualified_at");

                    b.Property<int?>("QualifiedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("qualified_by_user_id");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recording_url");

                    b.Property<string>("Revenus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revenus");

                    b.Property<int>("SourceFileContactId")
                        .HasColumnType("integer")
                        .HasColumnName("source_file_contact_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CampaignFileId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("SourceFileContactId");

                    b.ToTable("campaign_file_contacts");
                });

            modelBuilder.Entity("Backend.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("phone_prefix");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.LeadType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Code", "CountryId")
                        .IsUnique();

                    b.ToTable("lead_types", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.SourceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactCount")
                        .HasColumnType("integer")
                        .HasColumnName("contact_count");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer")
                        .HasColumnName("duplicates");

                    b.Property<int>("EmptyRows")
                        .HasColumnType("integer")
                        .HasColumnName("empty_rows");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileSizeLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_size_label");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("format");

                    b.Property<int>("InvalidPhones")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_phones");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSplitParent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_split_parent");

                    b.Property<int>("ListNumber")
                        .HasColumnType("integer")
                        .HasColumnName("list_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<int?>("ParentSourceFileId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_source_file_id");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<int?>("RecycledFromCampaignListId")
                        .HasColumnType("integer")
                        .HasColumnName("recycled_from_campaign_list_id");

                    b.Property<int?>("SplitPartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("split_part_number");

                    b.Property<int?>("SplitTotalParts")
                        .HasColumnType("integer")
                        .HasColumnName("split_total_parts");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer")
                        .HasColumnName("total_lines");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("ValidContacts")
                        .HasColumnType("integer")
                        .HasColumnName("valid_contacts");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentSourceFileId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("source_files", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.SourceFileContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("OriginalPhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_phone_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("integer")
                        .HasColumnName("source_file_id");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_source_file_contacts_phone_number");

                    b.HasIndex("SourceFileId")
                        .HasDatabaseName("idx_source_file_contacts_source_file_id");

                    b.ToTable("source_file_contacts", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("LeadTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadTypeId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<int?>("PasswordResetByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("password_reset_by_user_id");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("TypeContrat")
                        .HasColumnType("text")
                        .HasColumnName("type_contrat");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordResetByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.AgentProfile", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Backend.Entities.AgentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Campaign", b =>
                {
                    b.HasOne("Backend.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Backend.Entities.CampaignAgents", b =>
                {
                    b.HasOne("Backend.Entities.Campaign", "Campaign")
                        .WithMany("CampaignAgents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.CampaignFile", b =>
                {
                    b.HasOne("Backend.Entities.Campaign", "Campaign")
                        .WithMany("CampaignFiles")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.SourceFile", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("Backend.Entities.CampaignFileContact", b =>
                {
                    b.HasOne("Backend.Entities.User", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedAgentId");

                    b.HasOne("Backend.Entities.CampaignFile", "CampaignFile")
                        .WithMany()
                        .HasForeignKey("CampaignFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId");

                    b.HasOne("Backend.Entities.SourceFileContact", "SourceFileContact")
                        .WithMany()
                        .HasForeignKey("SourceFileContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("Campaign");

                    b.Navigation("CampaignFile");

                    b.Navigation("ConfirmedBy");

                    b.Navigation("SourceFileContact");
                });

            modelBuilder.Entity("Backend.Entities.LeadType", b =>
                {
                    b.HasOne("Backend.Entities.Country", "Country")
                        .WithMany("LeadTypes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Backend.Entities.RolePermission", b =>
                {
                    b.HasOne("Backend.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Entities.SourceFile", b =>
                {
                    b.HasOne("Backend.Entities.SourceFile", "ParentSourceFile")
                        .WithMany("ChildFiles")
                        .HasForeignKey("ParentSourceFileId");

                    b.HasOne("Backend.Entities.Supplier", "Supplier")
                        .WithMany("SourceFiles")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSourceFile");

                    b.Navigation("Supplier");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Backend.Entities.SourceFileContact", b =>
                {
                    b.HasOne("Backend.Entities.SourceFile", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_file_contacts_source_file");

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("Backend.Entities.Supplier", b =>
                {
                    b.HasOne("Backend.Entities.Country", "Country")
                        .WithMany("Suppliers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.LeadType", "LeadType")
                        .WithMany("Suppliers")
                        .HasForeignKey("LeadTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LeadType");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.HasOne("Backend.Entities.User", "PasswordResetBy")
                        .WithMany()
                        .HasForeignKey("PasswordResetByUserId");

                    b.HasOne("Backend.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PasswordResetBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignAgents");

                    b.Navigation("CampaignFiles");
                });

            modelBuilder.Entity("Backend.Entities.Country", b =>
                {
                    b.Navigation("LeadTypes");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Backend.Entities.LeadType", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Backend.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Entities.SourceFile", b =>
                {
                    b.Navigation("ChildFiles");
                });

            modelBuilder.Entity("Backend.Entities.Supplier", b =>
                {
                    b.Navigation("SourceFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
