-- ============================================================
-- Fix: Ajouter toutes les colonnes manquantes de Utilisateur
-- ============================================================

-- Auth features (AddAuthFeatures migration)
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "MustChangePassword" boolean NOT NULL DEFAULT false;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "RefreshToken" text;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "RefreshTokenExpiryTime" timestamp with time zone;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "PasswordResetToken" text;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "PasswordResetTokenExpiry" timestamp with time zone;

-- Cahier des charges: champs Agent (AddMissingCahierDesChargesFields)
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "DateEmbauche" timestamp with time zone;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "IsElite" boolean;
ALTER TABLE "Utilisateur" ADD COLUMN IF NOT EXISTS "Service" text;

-- Cahier des charges: champs Contact
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "NumGSM" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "CodePostal" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Ville" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "StatutAgent" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Commentaire" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "CommentaireConfirmation" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "CommentaireCommercial" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "CommentaireBanque" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Projet" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "TypeRendezVous" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "ProprietaireDepuis" timestamp with time zone;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "ModeChauffage" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "ConsommationChauffage" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "AgeChaudiere" integer;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "EtudePV" boolean;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "EquipePV" boolean;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "EquipePAC" boolean;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "EtatToiture" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "EtatIsolation" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Surface" double precision;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "NombrePersonnes" integer;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "ProfessionMr" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "ProfessionMme" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Credits" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Revenus" text;
ALTER TABLE "Contacts" ADD COLUMN IF NOT EXISTS "Fichage" boolean;

-- Cahier des charges: champs RendezVous
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "TypeRendezVous" text;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "CommentaireConfirmation" text;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "CommentaireCommercial" text;

-- Table Evaluations (si elle n'existe pas)
CREATE TABLE IF NOT EXISTS "Evaluations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AgentId" bigint NOT NULL,
    "EvaluateurId" bigint NOT NULL,
    "DateEvaluation" timestamp with time zone NOT NULL,
    "NotePitchCommercial" integer NOT NULL,
    "NoteTraitementObjections" integer NOT NULL,
    "NoteQualiteAppel" integer NOT NULL,
    "NoteRespectScript" integer NOT NULL,
    "NoteEcoute" integer NOT NULL,
    "NoteGlobale" double precision NOT NULL,
    "Commentaire" text,
    "AppelId" bigint,
    "NbRdvBrut" integer NOT NULL DEFAULT 0,
    "NbRdvConfirme" integer NOT NULL DEFAULT 0,
    "NbRdvAnnule" integer NOT NULL DEFAULT 0,
    "NbRdvSigne" integer NOT NULL DEFAULT 0,
    "NbPose" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Evaluations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evaluations_Utilisateur_AgentId"
        FOREIGN KEY ("AgentId") REFERENCES "Utilisateur"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Evaluations_Appels_AppelId"
        FOREIGN KEY ("AppelId") REFERENCES "Appels"("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Evaluations_AgentId" ON "Evaluations"("AgentId");
CREATE INDEX IF NOT EXISTS "IX_Evaluations_AppelId" ON "Evaluations"("AppelId");

SELECT 'Schema fix applied successfully!' AS result;
